name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (ex 1.0.1)'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@v3

  publish:
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          body: Please refer to [CHANGELOG.md](https://github.com/Ryujinx/Ryujinx-Website/blob/main/CHANGELOG.md) for details.
          token: ${{ secrets.CR_PAT }}
